"""empty message

Revision ID: 155cf843c6e0
Revises: 801101f3ff15
Create Date: 2020-08-12 21:38:19.301403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155cf843c6e0'
down_revision = '801101f3ff15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_available_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('availability_start', sa.DateTime(), nullable=False),
    sa.Column('availability_end', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Artist', sa.Column('always_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'always_available')
    op.drop_table('artist_available_times')
    # ### end Alembic commands ###
