"""empty message

Revision ID: 801101f3ff15
Revises: e3f39cabfe2d
Create Date: 2020-08-12 15:56:42.200971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801101f3ff15'
down_revision = 'e3f39cabfe2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
