"""empty message

Revision ID: e3f39cabfe2d
Revises: 2b1111065356
Create Date: 2020-08-12 14:31:18.453844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f39cabfe2d'
down_revision = '2b1111065356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
